Cargo.lock, ipvm-wasm/Cargo.toml, ipvm-wasm/src/wasmtime/ipld.rs, ipvm-wasm/src/wasmtime/world.rs, ipvm-wasm/tests/execute_wasm.rs, ipvm/Cargo.toml, ipvm/src/test_utils/db.rs, ipvm/src/test_utils/mod.rs, ipvm/src/workflow/receipt.rs, ipvm/tests/integration_test.rs
feat(ipld/wit): keep around tags for keyed representation vs kinded, use rc<refcell>
for interior mutability of vecdeque stack
fix(ipld/wit): more type-checking in general
refactor(ipld/wit): refactor to use refs more often
refactor(tests): way more tests and utils for testing, even db work for receipts
refactor(ipld/wit): threading store, linker
=> feat: rewrite for more complex types, including unions

.github/workflows/audit.yml, .github/workflows/coverage.yml, .github/workflows/nix.yml, .github/workflows/release.yml, .github/workflows/tests_and_checks.yml, .pre-commit-config.yaml, Cargo.lock, README.md, flake.nix, homestar-runtime/Cargo.toml, homestar-runtime/src/cli.rs, homestar-runtime/src/db.rs, homestar-runtime/src/event_handler.rs, homestar-runtime/src/event_handler/channel.rs, homestar-runtime/src/event_handler/error.rs, homestar-runtime/src/event_handler/event.rs, homestar-runtime/src/event_handler/swarm_event.rs, homestar-runtime/src/lib.rs, homestar-runtime/src/network/swarm.rs, homestar-runtime/src/network/ws.rs, homestar-runtime/src/runner.rs, homestar-runtime/src/scheduler.rs, homestar-runtime/src/settings.rs, homestar-runtime/src/tasks.rs, homestar-runtime/src/test_utils/event.rs, homestar-runtime/src/worker.rs, homestar-runtime/src/workflow.rs, homestar-runtime/src/workflow/info.rs, homestar-runtime/src/workflow/settings.rs
Includes:
* cargo docs pre-commit and ci
* more event / record handling
* backs up to provider if get_record (via put) fails
=> libp2p get providers and handle peer requests for records

flake.lock, homestar-runtime/src/db.rs, homestar-runtime/src/runner.rs, homestar-runtime/src/worker.rs, homestar-runtime/src/workflow/info.rs
This PR essentially makes progress count monotonic by changing up the inner join and storing receipt cids when grabbing info over libp2p.
=> refactor: move away from inner-join, count up unique receipts for workflow info

Cargo.lock, Cargo.toml, homestar-runtime/src/event_handler/swarm_event.rs, homestar-runtime/src/network/swarm.rs, homestar-runtime/src/settings.rs
As per a convo with @mriise, we should not add mdns peers as explicit peers. Instead, add them to kademlia.
=> refactor: for mdns, do not add explicit peer, just add to kademlia

.github/workflows/release.yml, .github/workflows/tests_and_checks.yml, Cargo.toml, homestar-runtime/fixtures/test_v4.toml, homestar-runtime/src/daemon.rs, homestar-runtime/src/runner.rs, homestar-runtime/tests/cli.rs
Adds code to capture windows signals in the runtime. Includes tests for starting and killing the runtime, also includes a change so github actions will build a windows container.
Fixes: [#183]
Please delete options that are not relevant.
Added a few tests into the CLI around testing both windows and non-windows functionality. Includes some ipv4 testing, daemon testing and windows signal testing.
=> Feat: Add capture for windows signals

homestar-runtime/fixtures/settings.toml, homestar-runtime/src/event_handler.rs, homestar-runtime/src/event_handler/swarm_event.rs, homestar-runtime/src/network/swarm.rs, homestar-runtime/src/settings.rs, homestar-runtime/tests/test_node1/config/settings.toml, homestar-runtime/tests/test_node2/config/settings.toml
Adds bootstrap nodes in settings that will be connected to on node startup.
Please add a link to any relevant issues/tickets.
Please delete options that are not relevant.
Parsing testing is added with the other settings test. Tests actually dialing nodes will be added in a different PR since this is a perquisite to gossip/receipt testing anyways.
=> Swarm Bootstrap Nodes

Cargo.toml
The `resolver` setting of `2` is implicit when using Rust 2021: https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
Build and run the tests. Everything should work without failures.
=> chore: Remove resolver setting

homestar-core/src/workflow/issuer.rs
`rs-ucan` misspells "principal" as "principle". We can alias to name this correctly, and we should eventually update the misspelling in `rs-ucan`.
Run the test suite. All tests should pass.
=> chore: Rename principle to principal

examples/websocket-relay/relay-app/src/components/Controls.svelte, examples/websocket-relay/relay-app/src/components/controls/Task.svelte, examples/websocket-relay/relay-app/src/components/controls/Workflow.svelte, examples/websocket-relay/relay-app/src/components/icons/Play.svelte, examples/websocket-relay/relay-app/src/lib/task.ts, examples/websocket-relay/relay-app/src/lib/workflow.ts, examples/websocket-relay/relay-app/src/stores.ts
We had an issue where Firefox would receive receipts over the Websocket channel nearly simultaneously which resulted in out-of-order errors. This PR fixes that by delaying the rendering of nodes until each previous task has completed and removing the error case.
The play button should be disabled when the other workflow is running. The button should not handle click events when in a spinner state.
Test in Firefox. No errors should be present and workflows should run and render as expected.
=> feat: Improve relay app node rendering and controls

.gitignore, .pre-commit-config.yaml, Cargo.lock, flake.nix, homestar-runtime/Cargo.toml, homestar-runtime/config/settings.toml, homestar-runtime/src/db.rs, homestar-runtime/src/lib.rs, homestar-runtime/src/metrics.rs, homestar-runtime/src/metrics/exporter.rs, homestar-runtime/src/metrics/node.rs, homestar-runtime/src/runner.rs, homestar-runtime/src/settings.rs, homestar-runtime/tests/cli.rs, homestar-runtime/tests/lib.rs, homestar-runtime/tests/metrics.rs, homestar-runtime/tests/test_node1/config/settings.toml, homestar-runtime/tests/test_node2/config/settings.toml, homestar-runtime/tests/utils.rs
This PR adds the following features:
Implements #184
We have an integration test in `homestar-runtime/tests/metrics.rs`.
=> feat: Add out-of-band node metrics

examples/websocket-relay/README.md
The README for the WebSocket Relay has some minor typographical errors
- [Before 🏚️](https://github.com/ipvm-wg/homestar/tree/main/examples/websocket-relay)
- [After 🏠](https://github.com/ipvm-wg/homestar/blob/fix-example-typo/examples/websocket-relay/README.md)
N/A
Look at it
Please add previews of any UI Changes.
=> fix: Websocket Relay README typos & formatting

examples/websocket-relay/relay-app/package-lock.json, flake.nix
Websocket example app depends on Nodejs, and (from a side conversation) a minimum version. This PR adds Node 18 LTS to to the Nix Flake, and rebuilds the Websocket relay lockfile. This means that if you run `nix develop`, you will have a consistent version of Node on your `PATH`.
`#worksonmymachine`?
=> Add Node 18 LTS to Flake for example frontends

.github/workflows/builds.yml, .github/workflows/coverage.yml, .github/workflows/docker.yml, Cross.toml, README.md, docker/Dockerfile, flake.lock, flake.nix, homestar-runtime/Cargo.toml, homestar-runtime/src/network/swarm.rs, homestar-runtime/tests/cli.rs, homestar-runtime/tests/fixtures/test_v4.toml, homestar-runtime/tests/fixtures/test_v4_alt.toml, homestar-runtime/tests/fixtures/test_workflow.toml, homestar-runtime/tests/metrics.rs
feat: builds via cross/rel
Closes https://github.com/ipvm-wg/homestar/issues/276. We'll open a new issue for more specific packages: brew, arch-linux, wix/windows. This will need some further testing to be absolutely sure, cc @walkah. 
Includes:
- Fixes bug with empty check on annouce_addresses
- local cross-rs setup for builds
- github action workflows: builds.yml tied to release
* builds binaries (cross if need be) for aarch64-unknown-linux-gnu, aarch64-unknown-linux-musl, aarch64-apple-darwin, x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin, x86_64-pc-windows-msvc, and x86_64-unknown-freebsd (for now)
* builds packages for .deb, .rpm (sets out todos for brew, wix, aur)
* docker push to ghcr.io and tag mult. versions
=> feat: builds, packages, pushing contains to ghcr

homestar-runtime/src/event_handler/swarm_event.rs, homestar-runtime/src/network/swarm.rs, homestar-runtime/src/settings.rs, homestar-runtime/tests/fixtures/test_mdns_connect1.toml, homestar-runtime/tests/fixtures/test_mdns_connect2.toml, homestar-runtime/tests/fixtures/test_network1.toml, homestar-runtime/tests/fixtures/test_network2.toml
This PR implements the following features:
These configs determine whether we toggle mDNS and Rendezvous on or off. In addition, we check the toggle states in event handlers where we might use mDNS or Rendezvous.
Closes #376 
All existing tests should pass. In particular, we are interested in the multi-node tests that rely on known peers and mDNS.
=> feat: Add mDNS and Rendezvous configs

.gitignore
There are committed `png` files, so we don't want to ignore all of them, right? 🤔 
Having files gitignored and committed confuses [release-plz](https://github.com/MarcoIeni/release-plz-action/issues/89). Is this a common pattern?
Usually I don't gitignore things I commit.
Committed png files: `["assets/a_logo.png", "examples/websocket-relay/synthcat.png"]`.
Remove the committed `.png`.
=> remove `*.png` from `.gitignore`

.github/workflows/nix.yml, .gitignore, examples/websocket-relay/README.md, flake.nix
Adding a default package definition to the flake (and also tests the build in CI)
Related to https://github.com/ipvm-wg/homestar/issues/362
Please delete options that are not relevant.
The `nix` workflow will now build the default homestar package
=> chore: add a nix package

.github/workflows/tests_and_checks.yml, homestar-runtime/src/event_handler/event.rs, homestar-runtime/src/network/webserver/rpc.rs, homestar-runtime/tests/network/notification.rs, homestar-runtime/tests/webserver.rs
-  [x] Refactor (non-breaking change that updates existing functionality)
Improved connection notification test included to move away from arbitrary waits to event-driven notification tests.
=> refactor: Fix connection notification test

Cross.toml, homestar-runtime/src/cli.rs, homestar-runtime/src/scheduler.rs, homestar-runtime/src/settings.rs, homestar-runtime/src/tasks/fetch.rs, homestar-runtime/src/worker.rs, homestar-runtime/src/workflow/settings.rs, homestar-wasm/src/wasmtime/error.rs, homestar-wasm/src/wasmtime/world.rs
Includes:
- also, add starter functions for default .pem/settings initialization
- error handling around retry, wasms
- ups the transport timeout
=> fix: make configuration run without -c (all defaults)

homestar-runtime/src/event_handler/event.rs, homestar-runtime/src/event_handler/swarm_event.rs, homestar-runtime/src/network/pubsub.rs, homestar-runtime/src/network/pubsub/message.rs, homestar-runtime/src/network/swarm.rs
The message wrapper includes a header with a nonce to force the gossip of duplicate receipts. We will likely expand on the header in future work and make the nonce optional.
Implements #421.
We've added a unit test to roundtrip a gossiped message to bytes and back again. We also have a gossip notifications integration test to confirm messages are still sent.
=> refactor: Add Gossipsub Message wrapper

homestar-runtime/tests/cli.rs, homestar-runtime/tests/metrics.rs, homestar-runtime/tests/network.rs, homestar-runtime/tests/network/notification.rs
The tests should pass and leave no databases behind.
=> chore: Remove databases after test runs

.github/workflows/builds.yml, homestar-runtime/src/event_handler.rs, homestar-runtime/src/event_handler/cache.rs, homestar-runtime/src/event_handler/channel.rs, homestar-runtime/src/event_handler/event.rs, homestar-runtime/src/event_handler/swarm_event.rs, homestar-runtime/src/network/rpc.rs, homestar-runtime/src/network/webserver.rs, homestar-runtime/src/network/webserver/rpc.rs, homestar-runtime/src/runner.rs, homestar-runtime/src/settings.rs, homestar-runtime/src/test_utils/event.rs, homestar-runtime/src/test_utils/worker_builder.rs, homestar-runtime/src/worker.rs, homestar-runtime/src/workflow/info.rs
Includes:
- a rename of `asyncboundedchannel*` to `asyncchannel` to accomodate unbounded channels
- remove receipt logging with too much output
=> chore: send_async where possible

homestar-runtime/src/runner.rs, homestar-runtime/src/runner/response.rs
This PR implements the following features:
The receipt table lists replayed receipt CIDs and associated instruction and invocation ran CIDs from a workflow run.
Run a workflow. The new table should be empty on first run.  Replayed receipt, instruction, and invocation ran CIDs should be displayed on subsequent runs.
With replayed receipts:
When no replayed receipts were available:
=> feat: Add CLI workflow run receipts table

homestar-runtime/config/defaults.toml, homestar-runtime/src/event_handler.rs, homestar-runtime/src/event_handler/cache.rs, homestar-runtime/src/event_handler/event.rs, homestar-runtime/src/event_handler/swarm_event.rs, homestar-runtime/src/settings/libp2p_config.rs, homestar-runtime/tests/network/notification.rs
=> feat: redial `node_addresses` at an interval on connection close

.github/workflows/tests_and_checks.yml, Cargo.lock, examples/websocket-relay/README.md, examples/websocket-relay/src/main.rs, homestar-runtime/Cargo.toml, homestar-runtime/build.rs, homestar-runtime/config/defaults.toml, homestar-runtime/src/cli.rs, homestar-runtime/src/cli/show.rs, homestar-runtime/src/event_handler.rs, homestar-runtime/src/event_handler/cache.rs, homestar-runtime/src/event_handler/event.rs, homestar-runtime/src/event_handler/swarm_event.rs, homestar-runtime/src/main.rs, homestar-runtime/src/network/rpc.rs, homestar-runtime/src/network/swarm.rs, homestar-runtime/src/network/webserver/rpc.rs, homestar-runtime/src/runner.rs, homestar-runtime/src/runner/nodeinfo.rs, homestar-runtime/src/runner/response.rs, homestar-runtime/src/settings/libp2p_config.rs, homestar-runtime/tests/cli.rs, homestar-runtime/tests/network.rs, homestar-runtime/tests/network/dht.rs, homestar-runtime/tests/network/gossip.rs, homestar-workspace-hack/Cargo.toml
fix: add handling of dns multiaddrs and added kad bootstrapping
Closes #545.
Closes #492. 
refactor: transport handling for ws & quic as fallback
Includes:
- dns fallback to cloudflare
- CLI: removal of -w for running workflows; it's now a positional argument (the first one on run)
* related to https://github.com/ipvm-wg/homestar/issues/489
- CLI: `node` command which showcases nodeinfo, e.g. peer_id and listener addrs/connections
* related to https://github.com/ipvm-wg/homestar/issues/489
- CLI: adds static/non-RPC `info` command showcasing version, build-git-sha, and features built with. We can extend this later with more build information. 
- Closes https://github.com/ipvm-wg/homestar/issues/297
- Closes https://github.com/ipvm-wg/homestar/issues/497
=> fix: add handling of dns multiaddrs + bootstrapping + CLI / Conn changes

.github/workflows/builds.yml, .github/workflows/docker.yml, .github/workflows/tests_and_checks.yml, DEVELOPMENT.md, docker/Dockerfile, flake.lock, flake.nix, homestar-runtime/build.rs, homestar-runtime/config/settings.toml, homestar-runtime/src/event_handler.rs, homestar-runtime/src/runner/response.rs
Includes:
- macos-14 for checks on ci
- some doc changes
- action-validator in flake for validation when changing github action workflows
- added a couple todos
=> refactor: docker updates with info command and rpc host update

DEVELOPMENT.md
Improves `wit-deps-cli` install command and links to `wasi-logging` repository.
=> docs: Improve wit-deps docs

homestar-runtime/tests/utils.rs
Allow dead default timeouts that triggered windows warnings. Keeping the default timeouts because we may use them in the future.
=> chore: Allow dead code default timeout

homestar-invocation/src/task/instruction/nonce.rs, homestar-runtime/src/runner/file.rs
This PR makes the following changes:
The schema will be updated by the schemas action, but as a preview it looks like this:
```json
"nnc": {
"description": "A 12-byte or 16-byte nonce encoded as IPLD bytes. Use empty string for no nonce.",
"oneOf": [
{
"$ref": "#/definitions/ipld_bytes"
},
{
"type": "string",
"const": ""
}
]
},
```
```json
"ipld_bytes": {
"title": "IPLD bytes",
"description": "Base64 encoded binary",
"type": "object",
"properties": {
"/": {
"type": "object",
"properties": {
"bytes": {
"type": "string"
}
}
}
}
},
```
A new `validate_and_parse_workflow_with_nonce` has been added that validates a workflow with a task that uses a nonce.
=> fix: Update nonce schema with IPLD bytes

Cargo.lock, README.md, homestar-wasm/Cargo.toml, homestar-wasm/README.md, homestar-wasm/src/wasmtime/ipld.rs, homestar-wasm/src/wasmtime/world.rs
This PR contains a spec/document for the WIT<->IPLD interpreter, which converts WIT runtime values to IPLD data model values based on WIT types. Consider this a living document on the state of the interpreter. 
Includes: 
- added testing 
- function name handling of varying cases
=> chore: doc interpreter

homestar-runtime/src/logger.rs, homestar-runtime/src/runner.rs, homestar-runtime/src/tasks/wasm.rs, homestar-runtime/src/worker.rs, homestar-runtime/src/worker/resolver.rs, homestar-wasm/src/wasmtime/host/helpers.rs, homestar-wasm/src/wasmtime/world.rs
Implements spans needed in #457
Run Homestar with `EVERY_CLI` set to `true` to see the simplified logs:
```
EVERY_CLI=true cargo run -- start
```
Check that `RUST_LOG` works when `EVERY_CLI` is `false` or not set:
```
EVERY_CLI=false RUST_LOG=info cargo run -- start
```
Running `test-workflow-add-one.json` with `EVERY_CLI` logs:
Same workflow, on replay:
A different workflow with WASI logging at `trace` level:
Error case where an arg with an unexpected type is passed to a workflow task:
=> refactor: Add workflow spans and every cli logging
